//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatWarriorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiguresOfPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FiguresOfPlayer()
        {
            this.FigureItemsByPlayers = new HashSet<FigureItemsByPlayer>();
        }
    
        public string Player_Email { get; set; }
        public string Figure_Name { get; set; }
        public Nullable<byte> Figure_Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FigureItemsByPlayer> FigureItemsByPlayers { get; set; }
        public virtual Figure Figure { get; set; }
        public virtual Player Player { get; set; }
    }
}
