//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatWarriorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiguresInGame
    {
        public string Player_One_Email { get; set; }
        public string Player_Two_Email { get; set; }
        public System.DateTime Game_Date { get; set; }
        public string Player_Email { get; set; }
        public string Figure_Name { get; set; }
        public Nullable<byte> Figure_Level { get; set; }
    
        public virtual Figure Figure { get; set; }
        public virtual GamesHistory GamesHistory { get; set; }
        public virtual Player Player { get; set; }
    }
}
