//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatWarriorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FigureItemsByPlayer
    {
        public string Player_Email { get; set; }
        public string Figure_Name { get; set; }
        public string FigureItem_Name { get; set; }
        public Nullable<byte> Item_Level { get; set; }
        public Nullable<byte> Figure_Attack { get; set; }
        public Nullable<byte> Figure_Defense { get; set; }
    
        public virtual FigureItem FigureItem { get; set; }
        public virtual FiguresOfPlayer FiguresOfPlayer { get; set; }
    }
}
