//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatWarriorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerGift
    {
        public int Gift_Code { get; set; }
        public string Player_Email { get; set; }
        public Nullable<byte> Gift_Level { get; set; }
        public Nullable<System.DateTime> Gift_Receive { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
